# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd34e021cd8d1c75aa87f9c4598458114c0af5f6093a8cff52abbd2ead2e88b018881bce0ec5c96ac3d09f5ba2396558d3828b4f4b405ea933d5944645ea0f11

test:
  secret_key_base: f92815b7c305d6f7789d5bce7e97b9087bcd0e20dc256616d074cceea928f626b587e3099f60696390ad36692dc892e185386d55543edc0b6663dc4c9c0abf9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
